apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-epts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-epts@sha256:0b24c11d5994228dc82432ee0ef1198720f6ddaba7f2723cb120fb7ac2b80f88
        name: my-nodejs
        resources: {}
status: {}
